export const cardData = {
    Tab1: [
      { id: 1, icon: '🔥', title: 'Card 1-1', summary: 'Summary 1-1', expandedSummary: 'Expanded Summary 1-1' },
      { id: 2, icon: '💧', title: 'Card 1-2', summary: 'Summary 1-2', expandedSummary: 'Expanded Summary 1-2' },
      { id: 3, icon: '🔥', title: 'Card 1-3', summary: 'Summary 1-3', expandedSummary: 'Expanded Summary 1-3' },
      { id: 4, icon: '💧', title: 'Card 1-4', summary: 'Summary 1-4', expandedSummary: 'Expanded Summary 1-4' },
      { id: 5, icon: '🔥', title: 'Card 1-5', summary: 'Summary 1-5', expandedSummary: 'Expanded Summary 1-5' },
      { id: 6, icon: '💧', title: 'Card 1-6', summary: 'Summary 1-6', expandedSummary: 'Expanded Summary 1-6' },
      { id: 7, icon: '🔥', title: 'Card 1-7', summary: 'Summary 1-7', expandedSummary: 'Expanded Summary 1-7' },
      { id: 8, icon: '💧', title: 'Card 1-8', summary: 'Summary 1-8', expandedSummary: 'Expanded Summary 1-8' },
      { id: 9, icon: '🔥', title: 'Card 1-9', summary: 'Summary 1-9', expandedSummary: 'Expanded Summary 1-9' },
      { id: 10, icon: '💧', title: 'Card 1-10', summary: 'Summary 1-10', expandedSummary: 'Expanded Summary 1-10' },
      { id: 11, icon: '🔥', title: 'Card 1-11', summary: 'Summary 1-11', expandedSummary: 'Expanded Summary 1-11' },
      { id: 12, icon: '💧', title: 'Card 1-12', summary: 'Summary 1-12', expandedSummary: 'Expanded Summary 1-12' },
      { id: 13, icon: '🔥', title: 'Card 1-13', summary: 'Summary 1-13', expandedSummary: 'Expanded Summary 1-13' },
      { id: 14, icon: '💧', title: 'Card 1-14', summary: 'Summary 1-14', expandedSummary: 'Expanded Summary 1-14' },
      { id: 15, icon: '🔥', title: 'Card 1-15', summary: 'Summary 1-15', expandedSummary: 'Expanded Summary 1-15' },
      { id: 16, icon: '💧', title: 'Card 1-16', summary: 'Summary 1-16', expandedSummary: 'Expanded Summary 1-16' },
      { id: 17, icon: '🔥', title: 'Card 1-17', summary: 'Summary 1-17', expandedSummary: 'Expanded Summary 1-17' },
      { id: 18, icon: '💧', title: 'Card 1-18', summary: 'Summary 1-18', expandedSummary: 'Expanded Summary 1-18' },
      { id: 19, icon: '🔥', title: 'Card 1-19', summary: 'Summary 1-19', expandedSummary: 'Expanded Summary 1-19' },
      { id: 20, icon: '💧', title: 'Card 1-20', summary: 'Summary 1-20', expandedSummary: 'Expanded Summary 1-20' },
      { id: 21, icon: '🔥', title: 'Card 1-21', summary: 'Summary 1-21', expandedSummary: 'Expanded Summary 1-21' },
      { id: 22, icon: '💧', title: 'Card 1-22', summary: 'Summary 1-22', expandedSummary: 'Expanded Summary 1-22' },
      { id: 23, icon: '🔥', title: 'Card 1-23', summary: 'Summary 1-23', expandedSummary: 'Expanded Summary 1-23' },
      { id: 24, icon: '💧', title: 'Card 1-24', summary: 'Summary 1-24', expandedSummary: 'Expanded Summary 1-24' }
    ],
    Tab2: [
      { id: 1, icon: '🌟', title: 'Card 2-1', summary: 'Summary 2-1', expandedSummary: 'Expanded Summary 2-1' },
      { id: 2, icon: '🌍', title: 'Card 2-2', summary: 'Summary 2-2', expandedSummary: 'Expanded Summary 2-2' },
      { id: 3, icon: '🌟', title: 'Card 2-3', summary: 'Summary 2-3', expandedSummary: 'Expanded Summary 2-3' },
      { id: 4, icon: '🌍', title: 'Card 2-4', summary: 'Summary 2-4', expandedSummary: 'Expanded Summary 2-4' },
      { id: 5, icon: '🌟', title: 'Card 2-5', summary: 'Summary 2-5', expandedSummary: 'Expanded Summary 2-5' },
      { id: 6, icon: '🌍', title: 'Card 2-6', summary: 'Summary 2-6', expandedSummary: 'Expanded Summary 2-6' },
      { id: 7, icon: '🌟', title: 'Card 2-7', summary: 'Summary 2-7', expandedSummary: 'Expanded Summary 2-7' },
      { id: 8, icon: '🌍', title: 'Card 2-8', summary: 'Summary 2-8', expandedSummary: 'Expanded Summary 2-8' },
      { id: 9, icon: '🌟', title: 'Card 2-9', summary: 'Summary 2-9', expandedSummary: 'Expanded Summary 2-9' },
      { id: 10, icon: '🌍', title: 'Card 2-10', summary: 'Summary 2-10', expandedSummary: 'Expanded Summary 2-10' },
      { id: 11, icon: '🌟', title: 'Card 2-11', summary: 'Summary 2-11', expandedSummary: 'Expanded Summary 2-11' },
      { id: 12, icon: '🌍', title: 'Card 2-12', summary: 'Summary 2-12', expandedSummary: 'Expanded Summary 2-12' },
      { id: 13, icon: '🌟', title: 'Card 2-13', summary: 'Summary 2-13', expandedSummary: 'Expanded Summary 2-13' },
      { id: 14, icon: '🌍', title: 'Card 2-14', summary: 'Summary 2-14', expandedSummary: 'Expanded Summary 2-14' },
      { id: 15, icon: '🌟', title: 'Card 2-15', summary: 'Summary 2-15', expandedSummary: 'Expanded Summary 2-15' },
      { id: 16, icon: '🌍', title: 'Card 2-16', summary: 'Summary 2-16', expandedSummary: 'Expanded Summary 2-16' },
      { id: 17, icon: '🌟', title: 'Card 2-17', summary: 'Summary 2-17', expandedSummary: 'Expanded Summary 2-17' },
      { id: 18, icon: '🌍', title: 'Card 2-18', summary: 'Summary 2-18', expandedSummary: 'Expanded Summary 2-18' },
      { id: 19, icon: '🌟', title: 'Card 2-19', summary: 'Summary 2-19', expandedSummary: 'Expanded Summary 2-19' },
      { id: 20, icon: '🌍', title: 'Card 2-20', summary: 'Summary 2-20', expandedSummary: 'Expanded Summary 2-20' },
      { id: 21, icon: '🌟', title: 'Card 2-21', summary: 'Summary 2-21', expandedSummary: 'Expanded Summary 2-21' },
      { id: 22, icon: '🌍', title: 'Card 2-22', summary: 'Summary 2-22', expandedSummary: 'Expanded Summary 2-22' },
      { id: 23, icon: '🌟', title: 'Card 2-23', summary: 'Summary 2-23', expandedSummary: 'Expanded Summary 2-23' },
      { id: 24, icon: '🌍', title: 'Card 2-24', summary: 'Summary 2-24', expandedSummary: 'Expanded Summary 2-24' }
    ],
    Tab3: [
      { id: 1, icon: '🚀', title: 'Card 3-1', summary: 'Summary 3-1', expandedSummary: 'Expanded Summary 3-1' },
      { id: 2, icon: '⚡', title: 'Card 3-2', summary: 'Summary 3-2', expandedSummary: 'Expanded Summary 3-2' },
      { id: 3, icon: '🚀', title: 'Card 3-3', summary: 'Summary 3-3', expandedSummary: 'Expanded Summary 3-3' },
      { id: 4, icon: '⚡', title: 'Card 3-4', summary: 'Summary 3-4', expandedSummary: 'Expanded Summary 3-4' },
      { id: 5, icon: '🚀', title: 'Card 3-5', summary: 'Summary 3-5', expandedSummary: 'Expanded Summary 3-5' },
      { id: 6, icon: '⚡', title: 'Card 3-6', summary: 'Summary 3-6', expandedSummary: 'Expanded Summary 3-6' },
      { id: 7, icon: '🚀', title: 'Card 3-7', summary: 'Summary 3-7', expandedSummary: 'Expanded Summary 3-7' },
      { id: 8, icon: '⚡', title: 'Card 3-8', summary: 'Summary 3-8', expandedSummary: 'Expanded Summary 3-8' },
      { id: 9, icon: '🚀', title: 'Card 3-9', summary: 'Summary 3-9', expandedSummary: 'Expanded Summary 3-9' },
      { id: 10, icon: '⚡', title: 'Card 3-10', summary: 'Summary 3-10', expandedSummary: 'Expanded Summary 3-10' },
      { id: 11, icon: '🚀', title: 'Card 3-11', summary: 'Summary 3-11', expandedSummary: 'Expanded Summary 3-11' },
      { id: 12, icon: '⚡', title: 'Card 3-12', summary: 'Summary 3-12', expandedSummary: 'Expanded Summary 3-12' },
      { id: 13, icon: '🚀', title: 'Card 3-13', summary: 'Summary 3-13', expandedSummary: 'Expanded Summary 3-13' },
      { id: 14, icon: '⚡', title: 'Card 3-14', summary: 'Summary 3-14', expandedSummary: 'Expanded Summary 3-14' },
      { id: 15, icon: '🚀', title: 'Card 3-15', summary: 'Summary 3-15', expandedSummary: 'Expanded Summary 3-15' },
      { id: 16, icon: '⚡', title: 'Card 3-16', summary: 'Summary 3-16', expandedSummary: 'Expanded Summary 3-16' },
      { id: 17, icon: '🚀', title: 'Card 3-17', summary: 'Summary 3-17', expandedSummary: 'Expanded Summary 3-17' },
      { id: 18, icon: '⚡', title: 'Card 3-18', summary: 'Summary 3-18', expandedSummary: 'Expanded Summary 3-18' },
      { id: 19, icon: '🚀', title: 'Card 3-19', summary: 'Summary 3-19', expandedSummary: 'Expanded Summary 3-19' },
      { id: 20, icon: '⚡', title: 'Card 3-20', summary: 'Summary 3-20', expandedSummary: 'Expanded Summary 3-20' },
      { id: 21, icon: '🚀', title: 'Card 3-21', summary: 'Summary 3-21', expandedSummary: 'Expanded Summary 3-21' },
      { id: 22, icon: '⚡', title: 'Card 3-22', summary: 'Summary 3-22', expandedSummary: 'Expanded Summary 3-22' },
      { id: 23, icon: '🚀', title: 'Card 3-23', summary: 'Summary 3-23', expandedSummary: 'Expanded Summary 3-23' },
      { id: 24, icon: '⚡', title: 'Card 3-24', summary: 'Summary 3-24', expandedSummary: 'Expanded Summary 3-24' }
    ]
  };
  